//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace iNAV.ws_test {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Test_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Test")]
    public partial class Test : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSalesOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFakeSalesOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Test() {
            //this.Url = "http://10.0.0.55:7047/DynamicsNAV/WS/CRONUS%20Italia%20S.p.A/Codeunit/Test";
            //this.Url = "http://tambov@eos.it:7047/DynamicsNAV/WS/CRONUS%20Italia%20S.p.A/Codeunit/Test";
            this.Url = "http://192.168.1.251:7047/DynamicsNAV/WS/CRONUS%20Italia%20S.p.A/Codeunit/Test";
            //this.Url = "http://192.168.0.14:7047/DynamicsNAV/WS/CRONUS%20Italia%20S.p.A/Codeunit/Test";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticationCompletedEventHandler AuthenticationCompleted;
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        public event CreateSalesOrderCompletedEventHandler CreateSalesOrderCompleted;
        
        /// <remarks/>
        public event CreateFakeSalesOrderCompletedEventHandler CreateFakeSalesOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Test:Authentication", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", ResponseElementName="Authentication_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool Authentication(string username, string password) {
            object[] results = this.Invoke("Authentication", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string username, string password) {
            this.AuthenticationAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string username, string password, object userState) {
            if ((this.AuthenticationOperationCompleted == null)) {
                this.AuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticationOperationCompleted);
            }
            this.InvokeAsync("Authentication", new object[] {
                        username,
                        password}, this.AuthenticationOperationCompleted, userState);
        }
        
        private void OnAuthenticationOperationCompleted(object arg) {
            if ((this.AuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticationCompleted(this, new AuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Test:GetItems", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", ResponseElementName="GetItems_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetItems(string search, ref rootItem itemPort) {
            object[] results = this.Invoke("GetItems", new object[] {
                        search,
                        itemPort});
            itemPort = ((rootItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(string search, rootItem itemPort) {
            this.GetItemsAsync(search, itemPort, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(string search, rootItem itemPort, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        search,
                        itemPort}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Test:GetCustomers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", ResponseElementName="GetCustomers_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCustomers(string search, ref rootCustomer customerPort) {
            object[] results = this.Invoke("GetCustomers", new object[] {
                        search,
                        customerPort});
            customerPort = ((rootCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync(string search, rootCustomer customerPort) {
            this.GetCustomersAsync(search, customerPort, null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(string search, rootCustomer customerPort, object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[] {
                        search,
                        customerPort}, this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Test:CreateSalesOrder", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", ResponseElementName="CreateSalesOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CreateSalesOrder(ref RootSalesHeader salesHeaderPort) {
            object[] results = this.Invoke("CreateSalesOrder", new object[] {
                        salesHeaderPort});
            salesHeaderPort = ((RootSalesHeader)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSalesOrderAsync(RootSalesHeader salesHeaderPort) {
            this.CreateSalesOrderAsync(salesHeaderPort, null);
        }
        
        /// <remarks/>
        public void CreateSalesOrderAsync(RootSalesHeader salesHeaderPort, object userState) {
            if ((this.CreateSalesOrderOperationCompleted == null)) {
                this.CreateSalesOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSalesOrderOperationCompleted);
            }
            this.InvokeAsync("CreateSalesOrder", new object[] {
                        salesHeaderPort}, this.CreateSalesOrderOperationCompleted, userState);
        }
        
        private void OnCreateSalesOrderOperationCompleted(object arg) {
            if ((this.CreateSalesOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSalesOrderCompleted(this, new CreateSalesOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Test:CreateFakeSalesOrder", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", ResponseElementName="CreateFakeSalesOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal CreateFakeSalesOrder(ref RootSalesHeader salesHeaderPort) {
            object[] results = this.Invoke("CreateFakeSalesOrder", new object[] {
                        salesHeaderPort});
            salesHeaderPort = ((RootSalesHeader)(results[1]));
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFakeSalesOrderAsync(RootSalesHeader salesHeaderPort) {
            this.CreateFakeSalesOrderAsync(salesHeaderPort, null);
        }
        
        /// <remarks/>
        public void CreateFakeSalesOrderAsync(RootSalesHeader salesHeaderPort, object userState) {
            if ((this.CreateFakeSalesOrderOperationCompleted == null)) {
                this.CreateFakeSalesOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFakeSalesOrderOperationCompleted);
            }
            this.InvokeAsync("CreateFakeSalesOrder", new object[] {
                        salesHeaderPort}, this.CreateFakeSalesOrderOperationCompleted, userState);
        }
        
        private void OnCreateFakeSalesOrderOperationCompleted(object arg) {
            if ((this.CreateFakeSalesOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFakeSalesOrderCompleted(this, new CreateFakeSalesOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50001")]
    public partial class rootItem {
        
        private Item[] itemField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public Item[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50001")]
    public partial class Item {
        
        private string no_Field;
        
        private string descriptionField;
        
        private string unit_List_PriceField;
        
        private string unit_PriceField;
        
        private string sales_Unit_of_MeasureField;
        
        /// <remarks/>
        public string No_ {
            get {
                return this.no_Field;
            }
            set {
                this.no_Field = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_List_Price {
            get {
                return this.unit_List_PriceField;
            }
            set {
                this.unit_List_PriceField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Unit_of_Measure {
            get {
                return this.sales_Unit_of_MeasureField;
            }
            set {
                this.sales_Unit_of_MeasureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/iNav")]
    public partial class Lines {
        
        private string typeField;
        
        private string noField;
        
        private decimal quantityField;
        
        private string unit_Of_Measure_CodeField;
        
        private decimal line_Discount_PctField;
        
        public Lines() {
            this.quantityField = ((decimal)(0m));
            this.line_Discount_PctField = ((decimal)(0m));
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_Of_Measure_Code {
            get {
                return this.unit_Of_Measure_CodeField;
            }
            set {
                this.unit_Of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Discount_Pct {
            get {
                return this.line_Discount_PctField;
            }
            set {
                this.line_Discount_PctField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/iNav")]
    public partial class SalesHeader {
        
        private string sell_To_Customer_NoField;
        
        private string payment_Terms_CodeField;
        
        private Lines[] linesField;
        
        /// <remarks/>
        public string Sell_To_Customer_No {
            get {
                return this.sell_To_Customer_NoField;
            }
            set {
                this.sell_To_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lines")]
        public Lines[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/iNav")]
    public partial class RootSalesHeader {
        
        private SalesHeader salesHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        public SalesHeader SalesHeader {
            get {
                return this.salesHeaderField;
            }
            set {
                this.salesHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class Customer {
        
        private string no_Field;
        
        private string nameField;
        
        private string addressField;
        
        private string address2Field;
        
        private string salesperson_CodeField;
        
        /// <remarks/>
        public string No_ {
            get {
                return this.no_Field;
            }
            set {
                this.no_Field = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50000")]
    public partial class rootCustomer {
        
        private Customer[] customerField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer")]
        public Customer[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AuthenticationCompletedEventHandler(object sender, AuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rootItem itemPort {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rootItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rootCustomer customerPort {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rootCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateSalesOrderCompletedEventHandler(object sender, CreateSalesOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSalesOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSalesOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RootSalesHeader salesHeaderPort {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootSalesHeader)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateFakeSalesOrderCompletedEventHandler(object sender, CreateFakeSalesOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFakeSalesOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFakeSalesOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RootSalesHeader salesHeaderPort {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootSalesHeader)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591