//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNAV
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int dashboard = 2131165184;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int listDragShadowBackground = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int menuIconCamera = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int menuIconShare = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int menuIconToggle = 2130771970;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int actionbar_background_dark = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_background_light = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int drag_active_color = 2130968578;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int titles_size = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int big_droid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_balloon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blue_bike = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_notification_ic_example = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_notification_ic_example_default = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_notification_ic_example_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int chrome_wheel = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cupcake = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int donut = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int eclair = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int froyo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int green_balloon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_camera_holo_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_camera_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_share_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_menu_share_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_menu_toggle_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_toggle_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_stat_notify_example = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notification_default_largeicon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int picture_frame_default = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int picture_frame_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int picture_frame_selected = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int punk_droid = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int rainbow_bike = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int red_balloon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Splash = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int stargazer_droid = 2130837533;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int Address = 2131361801;
			
			// aapt resource value: 0x7f0a0011
			public const int Amount = 2131361809;
			
			// aapt resource value: 0x7f0a000c
			public const int AmountItem = 2131361804;
			
			// aapt resource value: 0x7f0a0013
			public const int BasePrice = 2131361811;
			
			// aapt resource value: 0x7f0a0000
			public const int Desc1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int Desc2 = 2131361793;
			
			// aapt resource value: 0x7f0a000e
			public const int DescItem = 2131361806;
			
			// aapt resource value: 0x7f0a000a
			public const int Desc_Lay = 2131361802;
			
			// aapt resource value: 0x7f0a0017
			public const int Discount = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int Endprice = 2131361816;
			
			// aapt resource value: 0x7f0a0008
			public const int Name = 2131361800;
			
			// aapt resource value: 0x7f0a000f
			public const int NoItem = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int PriceItem = 2131361803;
			
			// aapt resource value: 0x7f0a0005
			public const int actv_Item = 2131361797;
			
			// aapt resource value: 0x7f0a002a
			public const int autocomplete = 2131361834;
			
			// aapt resource value: 0x7f0a0004
			public const int btnAdd_to_Cart = 2131361796;
			
			// aapt resource value: 0x7f0a002c
			public const int btnCancel = 2131361836;
			
			// aapt resource value: 0x7f0a001c
			public const int btnCancelOrder = 2131361820;
			
			// aapt resource value: 0x7f0a0020
			public const int btnLogin = 2131361824;
			
			// aapt resource value: 0x7f0a001b
			public const int btnOrder = 2131361819;
			
			// aapt resource value: 0x7f0a002b
			public const int btnSelect = 2131361835;
			
			// aapt resource value: 0x7f0a001a
			public const int button_frame = 2131361818;
			
			// aapt resource value: 0x7f0a0007
			public const int dashboardList = 2131361799;
			
			// aapt resource value: 0x7f0a0028
			public const int dialog_view = 2131361832;
			
			// aapt resource value: 0x7f0a0023
			public const int frag_content = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int frag_title = 2131361826;
			
			// aapt resource value: 0x7f0a0021
			public const int frags = 2131361825;
			
			// aapt resource value: 0x7f0a0010
			public const int itemName = 2131361808;
			
			// aapt resource value: 0x7f0a0002
			public const int linearLayout1 = 2131361794;
			
			// aapt resource value: 0x7f0a000d
			public const int linearLayout2 = 2131361805;
			
			// aapt resource value: 0x7f0a0027
			public const int notification_button = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int notification_subtitle = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int notification_title = 2131361829;
			
			// aapt resource value: 0x7f0a0024
			public const int notificationbg = 2131361828;
			
			// aapt resource value: 0x7f0a001d
			public const int relativeLayout1 = 2131361821;
			
			// aapt resource value: 0x7f0a0032
			public const int showCustomNotification = 2131361842;
			
			// aapt resource value: 0x7f0a0030
			public const int showDialog = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int showStandardNotification = 2131361841;
			
			// aapt resource value: 0x7f0a002d
			public const int switch_cam = 2131361837;
			
			// aapt resource value: 0x7f0a001e
			public const int tfLogin = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int tfPwd = 2131361823;
			
			// aapt resource value: 0x7f0a002f
			public const int toggleTheme = 2131361839;
			
			// aapt resource value: 0x7f0a002e
			public const int toggleTitles = 2131361838;
			
			// aapt resource value: 0x7f0a0012
			public const int txtAmount = 2131361810;
			
			// aapt resource value: 0x7f0a0014
			public const int txtBasePrice = 2131361812;
			
			// aapt resource value: 0x7f0a0016
			public const int txtDiscount = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int txtEndprice = 2131361817;
			
			// aapt resource value: 0x7f0a0003
			public const int txtItem = 2131361795;
			
			// aapt resource value: 0x7f0a0015
			public const int txtPerc = 2131361813;
			
			// aapt resource value: 0x7f0a0006
			public const int txtSelectedCustomer = 2131361798;
			
			// aapt resource value: 0x7f0a0029
			public const int txtfield = 2131361833;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar_custom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int autocomplete_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dashboard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int details = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_list_element = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Item_Order_Popup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layout1 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SetCustomer = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int title_list_item = 2130903051;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int camera_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int main_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int photo_context_menu = 2131296258;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060008
			public const int ApplicationName = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int app_widget_name = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int camera_sample = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int clip_label = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int notification_text = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int photo_selection_cab_title = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int widget_empty_view_text = 2131099653;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int ActionBar = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int ActionBar_Dark = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int ActionBar_Light = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int AppTheme_Dark = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int AppTheme_Light = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AppTheme = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int AppTheme_listDragShadowBackground = 0;
			
			// aapt resource value: 1
			public const int AppTheme_menuIconCamera = 1;
			
			// aapt resource value: 3
			public const int AppTheme_menuIconShare = 3;
			
			// aapt resource value: 2
			public const int AppTheme_menuIconToggle = 2;
			
			private Styleable()
			{
			}
		}
	}
}
